### ISSUE TITLE
How to query current search term, current replace term

### ISSUE THREAD

**Issue by JoeRoddy** [sereneinserenade/tiptap-extension-search-n-replace#2]
Great job on this extension @sereneinserenade , awesome work!

I have a find/replace button that hides and reveals itself and loses its state every time, but I want the find/replace to be persistent across every show/hide.  The extension correctly stores the find/replace terms, but I'm not sure if there's a good way to access them directly to fill in the inputs every time they're shown?  I know I can track this manually in react, but then I'd be managing the state in two places, rather than showing the true state inside the extension.

I'm guessing it's something like:
```javascript
editor.getAttributes('searchTerm');
```
but that^ comes up blank.

Any ideas how to achieve this?

**Comment by sereneinserenade** [comment]
> Great job on this extension, awesome work!

Thanks.

---

This repo doesn't contain the latest version of the extension, this was just an attempt to publish the extension to npm, but it was middling success.

You might wanna take a look at [this file](https://github.com/sereneinserenade/tiptap-search-n-replace-demo/blob/main/src/tiptap-extensions/searchAndReplace.ts). I've updated it so you can read the `searchTerm` and `replaceTerm` with [tiptap-storage](https://tiptap.dev/guide/custom-extensions/#storage).

Something like this would work

```ts
// ideally you should keep track of these states in your code, but if you absolutely need to read the `searchTerm` and `replaceTerm` from extension, here's the code
// reading searchTerm and replaceTerm from extension
const searchTerm: string = editor.storage.searchAndReplace.searchTerm
const replaceTerm: string = editor.storage.searchAndReplace.replaceTerm
```
